---
version: '2'
services:
  influxdb:
    build:
      context: ./influxdb
    privileged: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    build:
      context: ./grafana
    privileged: true
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    ports:
      - "3000:3000"
  telegraf:
    build:
      context: ./telegraf
    privileged: true
  kapacitor:
    build:
      context: ./kapacitor
    privileged: true
    ports:
      - "9092:9092"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
