---
version: '2'
services:
  nginx:
    build:
      context: ./nginx
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "80:80"
  influxdb:
    build:
      context: ./influxdb
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    build:
      context: ./grafana
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
    ports:
      - "3000:3000"
  telegraf:
    build:
      context: ./telegraf
  kapacitor:
    build:
      context: ./kapacitor
    ports:
      - "9092:9092"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
